### ISSUE TITLE
Add `Buffer` compatibility for browsers

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#765] opened 2023-02-06 13:34 UTC
We need to support `Buffer` usage inside the Browsers.

For example, someone using React with Vite might fall into this error:

![error](https://user-images.githubusercontent.com/26660/216984346-64db191d-efac-4dd5-9380-42a3d1312017.png)

And then having to resort to custom mapping configurations such by installing the `buffer` package:

```console
pnpm install buffer
```

And then configuring custom mappings in `vite.config.js`:

```ts
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  resolve: { alias: { buffer: 'node_modules/buffer/index.d.ts' } },
})
```

**Comment by arboleya** [comment] 2023-02-06 14:35
This might relate to the following PR, in the sense that the `Buffer` usages should fail for the browser group:
  - #728 

> cc @Dhaiwat10

**Comment by Dhaiwat10** [comment] 2023-02-07 09:01
@arboleya none of our browser tests are failing in #728. I am using [puppeteer](https://www.npmjs.com/package/puppeteer) to run the tests in a browser. Will need to investigate the difference between that environment and Vite. Do you have a repo containing a reproducible example that I can run locally to see this Vite error?

**Comment by arboleya** [comment] 2023-02-07 11:02
@Dhaiwat10 I created this issue from a conversation with @Braqzen.

@Braqzen Do you happen to have a simple repro for this problem?

**Comment by Braqzen** [comment] 2023-02-07 12:00
> @Dhaiwat10 I created this issue from a conversation with @Braqzen.
> 
> @Braqzen Do you happen to have a simple repro for this problem?

The steps are something like this (hopefully a repro):

1. pnpm create vite@latest ui --template react-ts
2. mkdir <root>/ui/src/contract-typegen
3. cd <root>/ui
4. pnpm install
5. pnpm install fuels --save
6. Generate contract typegen files with the fuels package by pointing at the generated /out/debug/<contract>-abi.json and placing them in the <root>/ui/src/contract-typegen directory

The contract that I have is a simple counter. It has a single storage variable which is incremented and decremented by 1 when the function is called. It has a couple more functions but I doubt they matter.
I think you need to import the wallet from fuels and potentially have some code to call a function from the contract in a `.tsx` file in order for it to trigger.
Try starting the server and opening it in the browser at this point and the I believe the error should pop up in the console of the browser. If not then I can create a local repository and link it here.

**Comment by Dhaiwat10** [comment] 2023-02-09 16:10
Yeah, Vite is one of the few 'popular' setups that don't polyfill these things. I believe that's the reason why none of our tests are failing in #728 when run in a browser environment - it uses puppeteer which runs a headless version of Chromium under the hood.

**Comment by arboleya** [comment] 2023-02-09 18:05
@Braqzen In which browser have you had this problem?

@camsjams Why do you think we should not add [buffer](https://github.com/feross/buffer) as a dependency? I wonder if Polyfills should be required _only_ for libraries there were not _originally_ planned to run inside the Browser.

**Comment by Braqzen** [comment] 2023-02-09 18:13
> @Braqzen In which browser have you had this problem?
> 
> @camsjams Why do you think we should not add [buffer](https://github.com/feross/buffer) as a dependency? I wonder if Polyfills should be required _only_ for libraries there were not _originally_ planned to run inside the Browser.

I was running things in Chromium.

**Comment by arboleya** [comment] 2023-06-05 15:26
Probably related:
 - https://github.com/FuelLabs/fuels-ts/issues/765

**Comment by danielbate** [comment] 2023-09-07 10:57
We will need to polyfill `Buffer` (along with other Node environment deps) should we want to configure a complete browser testing environment that Vite offers. Unlike the browser-like environment that puppeteer and playwright offer. Also relates to #721

**Comment by danielbate** [comment] 2024-01-15 11:47
So for browser testing in #1630, I went down the consumer configuration route, rather than introducing the polyfill our side. Purely from the stance of trying to introduce minimal interruption to the packages themselves, and only changing the test infrastructure. On doing some digging, this is what's [recommended](https://github.com/w3ctag/polyfills/issues/6#issuecomment-272647475) rather than attempting to account for it on our side.

I did have success in polyfilling it our side via `tsup` configuration with an `esbuild` injection if we want to go down that route. 

I could also do an example with documentation based on the `vite` configuration that we have used for browser testing. However I don't think I will go any further in #1630 given we now have a setup with minimal interruption.

**Comment by arboleya** [comment] 2024-07-20 00:48
@FuelLabs/sdk-ts Pretty old one - is this still valid?

**Comment by danielbate** [comment] 2024-07-22 06:53
@nedsalk and I chatted around the browser testing time and ended up opting to polyfill at the app level, as we do with the browser tests. [This discussion](https://github.com/w3ctag/polyfills/issues/6#issuecomment-272647475) sums it up well.

Going to close this for now as we've gone back and fourth quite a bit, it could be revisited if raised by users but it's not a blocker as an app dev can resolve it.

**Closed by danielbate** 2024-07-22 06:53 UTC
Labels: bug
