### ISSUE TITLE
contract call not considering `txParams`

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-ts#2257] opened 2024-05-07 18:22 UTC
### What version of fuels-ts are you using?

0.84.0

### Steps to Reproduce

![image](https://github.com/FuelLabs/fuels-ts/assets/8636507/390e8da7-ec41-4375-992d-2c4825efa011)

execute a contract function and try to inform `txParams`

### Expected Behavior

SDK should respect the value that user sends

### Actual Behavior

`gasLimit` and `maxFee` are calculated and set no matter what you pass

**Comment by arboleya** [comment] 2024-05-08 10:33
Possible duplicate of https://github.com/FuelLabs/fuels-ts/issues/2243.

**Closed** 2024-05-10 12:51 UTC
Labels: bug, mainnet
