### ISSUE TITLE
Configure ScriptCallHandler's inputs and outputs as in rust sdk

### ISSUE THREAD

**Issue by chlenc** [FuelLabs/fuels-ts#1020] opened 2023-05-26 13:24 UTC
### Motivation

Hi there
In our CLOB on predicates in a few cases like fulfillment or cancelation of order, we should have the possibility to configure `ScriptCallHandler` with `inputs` and `outputs`

Here is the `cancel_order` func on Rust language using Rust SDK

```rs
 pub async fn cancel_order(
        predicate: &Predicate,
        wallet: &WalletUnlocked,
        asset0: AssetId,
        amount0: u64,
    ) -> Result<FuelCallResponse<()>, fuels::prelude::Error> {
        let provider = wallet.provider().unwrap();

        let inputs = predicate
            .clone()
            .set_provider(provider.clone())
            .get_asset_inputs_for_amount(asset0, amount0, None)
            .await
            .unwrap();

        let outputs = wallet.get_asset_outputs_for_amount(wallet.address(), asset0, 0);
        println!("inputs = {:?}", inputs);
        println!("outputs = {:?}", outputs);
        let script_call = ScriptCallHandler::new(
            vec![],
            UnresolvedBytes::default(),
            wallet.clone(),
            provider.clone(),
            Default::default(),
        )
        .with_inputs(inputs)
        .with_outputs(outputs)
        .tx_params(TxParameters::default().set_gas_price(1));

        script_call.call().await
    }
```

logs will be like that

```
alice_address = 0xccc4f9249536cf89ab0f31bb52fa06c00ea0387dcac5830924ecf56f2dded3a5
Predicate root = Bech32Address { hrp: "fuel", hash: c04e498ac26cbff0b93d9c218cf8bdc18e1190953ef5f3e5ace8146deded519c }
USDC AssetId (asset0) = 0x56fb8789a590ea9c12af6fe6dc2b43f347700b049d4f823fd4476c6f366af201
UNI AssetId (asset1) = 0x5381bbd1cff41519062c8531ec30e8ea1a2d752e59e4ac884068d3821e9f0093
    

    inputs = [
        ResourcePredicate { 
            resource: Coin(Coin {
                 amount: 1000000000, 
                 block_created: 766024, 
                 asset_id: 56fb8789a590ea9c12af6fe6dc2b43f347700b049d4f823fd4476c6f366af201, 
                 utxo_id: UtxoId { tx_id: 2744628915b0d89ca8e79133a4598f72b32be9e884a723dad67a56c882da48ff, output_index: 2 }, 
                 maturity: 0, 
                 owner: Bech32Address { hrp: "fuel", hash: c04e498ac26cbff0b93d9c218cf8bdc18e1190953ef5f3e5ace8146deded519c }, 
                 status: Unspent 
                }), 
            code: [...], 
            data: UnresolvedBytes { data: [] } 
        }
    ]

    outputs = [
        Coin { 
            to: ccc4f9249536cf89ab0f31bb52fa06c00ea0387dcac5830924ecf56f2dded3a5, 
            amount: 0, 
            asset_id: 56fb8789a590ea9c12af6fe6dc2b43f347700b049d4f823fd4476c6f366af201 
        }, 
        Change { 
            to: ccc4f9249536cf89ab0f31bb52fa06c00ea0387dcac5830924ecf56f2dded3a5, 
            amount: 0, 
            asset_id: 56fb8789a590ea9c12af6fe6dc2b43f347700b049d4f823fd4476c6f366af201 
        }
    ]

```

In the predicate, this code is in charge of cancelation 
```rs
    let mut i = 0u8;
    let inputs: u8 = input_count();
    while i < inputs  {
        if input_owner(i).unwrap() == Address::from(MAKER) {
            return true;
        }
        i += 1u8;
    }
```

So, ts-sdk has func `` that can help us to make cancelation:
```
const cancelTx = await wallet.transfer(predicate.address, 0, token0.assetId, {
    gasPrice: 1,
  });
await cancelTx.waitForResult();
```

We did this script to test that

```ts
import BN from "../src/utils/BN";
import { TOKENS_BY_SYMBOL } from "../src/constants";
import { LimitOrderPredicateAbi__factory } from "../src/predicates";
import { Predicate, Provider, Wallet } from "fuels";
import { nodeUrl, privateKey } from "../src/config";

(async () => {
  const token0 = TOKENS_BY_SYMBOL.USDC;
  const amount0 = BN.parseUnits(20, token0.decimals);
  const token1 = TOKENS_BY_SYMBOL.BTC;
  const amount1 = BN.parseUnits(0.001, token1.decimals);
  const exp = BN.parseUnits(1, 9 + token0.decimals - token1.decimals);
  let price = amount1.times(exp).div(amount0);

  const wallet = Wallet.fromPrivateKey(privateKey, nodeUrl);

  // console.log(price.toString());
  const configurableConstants = {
    ASSET0: token0.assetId,
    ASSET1: token1.assetId,
    MAKER: wallet.address.toB256(),
    PRICE: price.toFixed(0),
    ASSET0_DECINALS: token0.decimals,
    ASSET1_DECINALS: token1.decimals,
  };
  console.log(configurableConstants);
  const predicate = new Predicate(
    LimitOrderPredicateAbi__factory.bin,
    LimitOrderPredicateAbi__factory.abi,
    new Provider(nodeUrl),
    configurableConstants
  );

  console.log(predicate.address.toB256());

  const initialPredicateBalance = await predicate.getBalance(token0.assetId);
  console.log("initialPredicateBalance", initialPredicateBalance.toString());

  const depositTx = await wallet
    .transfer(predicate.address, amount0.toFixed(0), token0.assetId, { gasPrice: 1 })
    .catch((e) => console.error(`depositTx ${e}`));
  await depositTx?.waitForResult();
  //
  const feeTx = await wallet
    .transfer(predicate.address, 1, TOKENS_BY_SYMBOL.ETH.assetId, { gasPrice: 1 })
    .catch((e) => console.error(`feeTx ${e}`));
  await feeTx?.waitForResult();

  const predicateBalances = await predicate.getBalances();
  console.log(
    "predicateBalances",
    predicateBalances.map((v) => ({
      amount: v.amount.toString(),
      assetId: v.assetId.toString(),
    }))
  );
  //---------------------
  const cancelTx = await wallet.transfer(predicate.address, 0, token0.assetId, {
    gasPrice: 1,
  });
  await cancelTx.waitForResult();

  const finalPredicateBalance = await predicate.getBalances();
  console.log(
    "finalPredicateBalance",
    finalPredicateBalance.map((v) => v.amount.toString())
  );
})();

```

But this test fails with this error
```
/Users/alexey/projects/spark-ts-sdk/node_modules/graphql-request/src/index.ts:441
    throw new ClientError(
          ^
ClientError: TransactionOutputCoinAssetIdNotFound(56fb8789a590ea9c12af6fe6dc2b43f347700b049d4f823fd4476c6f366af201): {"response":{"data":null,"errors":[{"message":"TransactionOutputCoinAssetIdNotFound(56fb8789a590ea9c12af6fe6dc2b43f347700b049d4f823fd4476c6f366af201)","locations":[{"line":2,"column":3}],"path":["dryRun"]}],"status":200,"headers":{}},"request":{"query":"mutation dryRun($encodedTransaction: HexString!, $utxoValidation: Boolean) {\n  dryRun(tx: $encodedTransaction, utxoValidation: $utxoValidation) {\n    ...receiptFragment\n  }\n}\n\nfragment receiptFragment on Receipt {\n  data\n  rawPayload\n}","variables":{"encodedTransaction":"0x000000000000000000000000000000010000000005f5e1000000000000000000000000000000000400000000000000000000000000000001000000000000000200000000000000010000000000000000000000000000000000000000000000000000000000000000240000000000000000000000000000009835cda5c81ed1492fe4dc3696a7b39b6e94ac2c3ba4f739bafc69562061b31700000000000000042ce05bde9ada2d2c58b5eb9f08be34df19375d618626c324f75dfdbd226c8d8800000000000004300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000057fe0ee890797038951426b07a7c0f16d135635e0bc27cae1461aae80ca6b7e6000000000000000056fb8789a590ea9c12af6fe6dc2b43f347700b049d4f823fd4476c6f366af20100000000000000032ce05bde9ada2d2c58b5eb9f08be34df19375d618626c324f75dfdbd226c8d88000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","utxoValidation":false}}}
    at makeRequest (/Users/alexey/projects/spark-ts-sdk/node_modules/graphql-request/src/index.ts:441:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async H.estimateTxDependencies (/Users/alexey/projects/spark-ts-sdk/node_modules/@fuel-ts/providers/src/provider.ts:387:39)
    at async n.sendTransaction (/Users/alexey/projects/spark-ts-sdk/node_modules/@fuel-ts/wallet/src/base-unlocked-wallet.ts:85:5) {
  response: {
    data: null,
    errors: [ [Object] ],
    status: 200,
    headers: Headers { [Symbol(map)]: [Object: null prototype] }
  },
  request: {
    query: 'mutation dryRun($encodedTransaction: HexString!, $utxoValidation: Boolean) {\n' +
      '  dryRun(tx: $encodedTransaction, utxoValidation: $utxoValidation) {\n' +
      '    ...receiptFragment\n' +
      '  }\n' +
      '}\n' +
      '\n' +
      'fragment receiptFragment on Receipt {\n' +
      '  data\n' +
      '  rawPayload\n' +
      '}',
    variables: {
      encodedTransaction: '0x000000000000000000000000000000010000000005f5e1000000000000000000000000000000000400000000000000000000000000000001000000000000000200000000000000010000000000000000000000000000000000000000000000000000000000000000240000000000000000000000000000009835cda5c81ed1492fe4dc3696a7b39b6e94ac2c3ba4f739bafc69562061b31700000000000000042ce05bde9ada2d2c58b5eb9f08be34df19375d618626c324f75dfdbd226c8d8800000000000004300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000057fe0ee890797038951426b07a7c0f16d135635e0bc27cae1461aae80ca6b7e6000000000000000056fb8789a590ea9c12af6fe6dc2b43f347700b049d4f823fd4476c6f366af20100000000000000032ce05bde9ada2d2c58b5eb9f08be34df19375d618626c324f75dfdbd226c8d88000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
      utxoValidation: false
    }
  }
}

```

Forum topics:
https://forum.fuel.network/t/how-to-configure-predicate-calls-inputs-and-outputs-in-ts-sdk/2688
https://forum.fuel.network/t/how-to-get-asset-outputs-for-amount-and-get-asset-inputs-for-amount-with-ts-dsk/2638

### Usage example

```
async function cancelOrder(
    predicate: Predicate<[]>, //not sure about type
    wallet: WalletUnlocked,
    asset0: string,
    amount0: BN,
) {
    let inputs = await predicate.getAssetInputsForAmount(asset0, amount0)
    let outputs = wallet.getAssetOutputsForAmount(wallet.address, asset0, 0);
    let scriptCall = new ScriptCallHandler(
        [], //script binary
        UnresolvedBytes.default(), //encoded args
        wallet, //account
        wallet.provider,//provider
    )
    scriptCall
        .with_inputs(inputs)
        .with_outputs(outputs)
        .tx_params(TxParameters.default().set_gas_price(1));

    await scriptCall.call()
}
```

**Comment by mauricewbr** [comment] 2023-05-30 08:45
I can second that. The discrepancy of handling inputs / outputs between Rust SDK and TS SDK has been confusing to us too.

**Comment by chlenc** [comment] 2023-06-06 17:38
+1

**Comment by danielbate** [comment] 2023-06-07 11:20
@chlenc @mauricewbr thanks for your input both, I can appreciate your frustrations with the discrepancies but firstly I want to ensure that we aren't already covering these functionalities and that the above error isn't masking a different issue in the code. But regardless, this does highlight that we either need to improve the documentation or dev experience of this functionality. Firstly, let's step through these points as there is a few here from my point of view:

We have a `ScriptTransactionRequest` available in the `providers` package. We can see it at work in the `Account.transfer` function, which is also the same `transfer` functionality utilised by a Predicate in the TS SDK as it extends an `Account`:

https://github.com/FuelLabs/fuels-ts/blob/bc0594e56b64aef05a50b4982a816c299f610d63/packages/wallet/src/account.ts#L176-L207

Here we can see `addResources` and `addCoinOutput` being called on the transaction request instance to set inputs and outputs respectively. Potentially some refactoring could be done here to bring this nomenclature in line with the Rust SDK? Here you would be able to build out your own transaction and set your own inputs and outputs and call your own transaction through `Predicate.sendTransaction(myScriptTransactionRequest)`. However, like I said, as `predicate.transfer` is making use of this functionality, I'm unsure why you would be receiving that error as it seems to be already covered by test cases.

Additionally, in your above exemplar script, you are only ever calling `wallet.transfer`, never `predicate.transfer` so we have not evaluated the predicate and in each call would just be funding the predicate again.

I'm keen to make an improvement here so let me know your thoughts on the above.

**Comment by danielbate** [comment] 2023-06-07 16:02
@chlenc I've written a new test case [here](https://github.com/FuelLabs/fuels-ts/blob/dfaedd2e80406667a214099787eaf0d45999f6e9/packages/fuel-gauge/src/predicate-with-script-handler.test.ts) that shows a predicate utilising a script transaction request. Very similar to the above apart from instantiating and funding the predicate rather than passing it to a function.

**Comment by Torres-ssf** [comment] 2023-06-07 18:10
Hey, @chlenc, could you clarify what exactly this script call is attempting to achieve? From my understanding, it seems to be trying to transfer the UTXO owned by a predicate back to the original owner.

I noticed that you've provided a code snippet using the Rust-SDK. Could you confirm whether this approach was successful with the Rust SDK?

I plan to reproduce this using the Rust SDK to better understand it, and then figure out how it can be implemented in the TS SDK.

**Comment by chlenc** [comment] 2023-06-07 18:19
Also you can see find remastered version of predicate here
https://github.com/compolabs/ethglobal-predicate/blob/58ac7ef13faaaf84cddfa7d199fa88be359834c8/limit-order-predicate/src/main.sw#L30

**Comment by Torres-ssf** [comment] 2023-06-11 23:34
@chlenc I have identified the problem.

When the SDK fetches resources (UTXOs) for use in the transaction, passing an amount of `0` for the asset results in no UTXOs for the same asset being returned. This issue does not occur when transferring the native asset with a value of `0` since the transaction fees are paid with the native asset and therefore, its amount is never `0`.

I need to consider the best way to address this issue in the SDK. In the meantime, you can manually create a transaction request that accomplishes what you're trying to do by following the code provided in this [gist here](https://gist.github.com/Torres-ssf/ac1558d8e0ccaf25074a6fe4e5014e6b)

**Comment by Torres-ssf** [comment] 2023-06-14 18:46
@lzhabo Sorry that you are running into these errors

About the errors:

1 - This is indeed a feature pending implementation. I am planning to work on that in the near future.

2 - It's really odd that you are running into `Transaction is not inserted. UTXO is not existing`. I've just tried a similar approach at my side and it's working as expected. I will continue to try to figure out what is the source of the problem. 

In the meantime, can you give me more context about your use case? A question that might help me to better understand what is going on and how I can help you to achieve what you are trying to do is:

1 - In the original code provided here, I can see that it tries to transfer the amount of `0` from a wallet to a predicate. Do you also need to transfer an amount of `0` to a predicate? Why?

**Comment by chlenc** [comment] 2023-06-14 22:15
> @lzhabo Sorry that you are running into these errors
> 
> About the errors:
> 
> 1 - This is indeed a feature pending implementation. I am planning to work on that in the near future.
> 
> 2 - It's really odd that you are running into `Transaction is not inserted. UTXO is not existing`. I've just tried a similar approach at my side and it's working as expected. I will continue to try to figure out what is the source of the problem.
> 
> In the meantime, can you give me more context about your use case? A question that might help me to better understand what is going on and how I can help you to achieve what you are trying to do is:
> 
> 1 - In the original code provided here, I can see that it tries to transfer the amount of `0` from a wallet to a predicate. Do you also need to transfer an amount of `0` to a predicate? Why?

It's a cancelation of an order, when we transfer 0 of an asset from a maker side it canceled an order. You can see the code right here:
https://github.com/compolabs/ethglobal-predicate/blob/58ac7ef13faaaf84cddfa7d199fa88be359834c8/limit-order-predicate/src/main.sw#L30

I have inspired by code from the OTC swap
https://github.com/FuelLabs/sway-applications/blob/5431f0ae8674175b162e3754efc996285cb04b28/OTC-swap-predicate/project/predicates/swap-predicate/src/main.sw#L31

**Comment by Torres-ssf** [comment] 2023-06-15 15:41
Has this approach been validated already? I cannot see how this is going to work. 

From what I understood, the `std::inputs::{input_owner}` method is going to return the address that has ownership on the UTXO present on the `inputs` of the transaction, which in the case of the provided Rust function `cancel_order`, it's the predicate itself. 

In the specific case of the script that is being created by `cancel_order`, the only input (UTXO) present in the transaction is owned by the Predicate. This basically means that when the script executes the predicate call, the `input_owner(0)` will be always equal to the predicate address, because it is the predicate that owns the input UTXO. This can be validated in the given logs, the only input is the predicate itself.

I've also noticed another thing, It was also given a TS version that tries to mimic what is happening on `cancel_order`:
```ts
const cancelTx = await wallet.transfer(predicate.address, 0, token0.assetId, {
    gasPrice: 1,
  });

await cancelTx.waitForResult();
```

But unfortunately, this code does not execute the predicate at all. 

What it does is simply create a script to transfer assets from the caller's wallet to the predicate address. That's it, if you execute the previous code (with an amount higher than `0`), it will spend UTXOs owned by the wallet callers to transfer them to the predicate, generating now new UTXOs owned by the predicate. 

But the predicate validation never happens. 

In order to execute the predicate call in the same way that is happening on `cancel_order` we would need to do something like this:

```ts
const tx = await predicate.transfer(wallet.address, 0, nativeAssetId);

await tx.waitForResult()
```

This code will do among other things: 

1 - Fetch one or more UTXOs owned by the predicate with the sum of amount enough to satisfy this transaction, in this case, `0 + transactionFee`
2 - Add the predicate UTXO (or UTXOs) to the inputs of the transaction.
3 - Add an Output of type `Coin`, with the amount of `0` addressed to the wallet (can be seen on the given log)
4 - Add an Output of type `Change` addressed to the predicate (can be seen on the given log)
5 - Then will execute the script that will execute the predicate

**Comment by chlenc** [comment] 2023-06-15 18:24
> Has this approach been validated already? I cannot see how this is going to work.
> 
> From what I understood, the `std::inputs::{input_owner}` method is going to return the address that has ownership on the UTXO present on the `inputs` of the transaction, which in the case of the provided Rust function `cancel_order`, it's the predicate itself.
> 
> In the specific case of the script that is being created by `cancel_order`, the only input (UTXO) present in the transaction is owned by the Predicate. This basically means that when the script executes the predicate call, the `input_owner(0)` will be always equal to the predicate address, because it is the predicate that owns the input UTXO. This can be validated in the given logs, the only input is the predicate itself.
> 
> I've also noticed another thing, It was also given a TS version that tries to mimic what is happening on `cancel_order`:
> 
> ```ts
> const cancelTx = await wallet.transfer(predicate.address, 0, token0.assetId, {
>     gasPrice: 1,
>   });
> 
> await cancelTx.waitForResult();
> ```
> 
> But unfortunately, this code does not execute the predicate at all.
> 
> What it does is simply create a script to transfer assets from the caller's wallet to the predicate address. That's it, if you execute the previous code (with an amount higher than `0`), it will spend UTXOs owned by the wallet callers to transfer them to the predicate, generating now new UTXOs owned by the predicate.
> 
> But the predicate validation never happens.
> 
> In order to execute the predicate call in the same way that is happening on `cancel_order` we would need to do something like this:
> 
> ```ts
> const tx = await predicate.transfer(wallet.address, 0, nativeAssetId);
> 
> await tx.waitForResult()
> ```
> 
> This code will do among other things:
> 
> 1 - Fetch one or more UTXOs owned by the predicate with the sum of amount enough to satisfy this transaction, in this case, `0 + transactionFee` 2 - Add the predicate UTXO (or UTXOs) to the inputs of the transaction. 3 - Add an Output of type `Coin`, with the amount of `0` addressed to the wallet (can be seen on the given log) 4 - Add an Output of type `Change` addressed to the predicate (can be seen on the given log) 5 - Then will execute the script that will execute the predicate

I’m tried this before. The problem is we don’t have input from maker (wallet)
’’’

const tx = await predicate.transfer(wallet.address, 0, nativeAssetId);

await tx.waitForResult()
’’’

**Comment by Torres-ssf** [comment] 2023-06-19 17:13
@chlenc @lzhabo, could I have more context about the transaction that executes the `cancel order` predicate?

This transaction will need to be created manually. I can provide a gist outlining the necessary steps, but to do so, I need a comprehensive understanding of all actions that should occur within this transaction."

**Comment by chlenc** [comment] 2023-06-19 17:18
@Torres-ssf this is the same mechanism as here 
https://github.com/FuelLabs/sway-applications/blob/5431f0ae8674175b162e3754efc996285cb04b28/OTC-swap-predicate/project/predicates/swap-predicate/src/main.sw#L31

**Comment by chlenc** [comment] 2023-06-19 17:24
> @chlenc @lzhabo, could I have more context about the transaction that executes the `cancel order` predicate?
> 
> This transaction will need to be created manually. I can provide a gist outlining the necessary steps, but to do so, I need a comprehensive understanding of all actions that should occur within this transaction.

can you tell me specifically what information besides this I can provide? maybe we should call?

**Comment by Torres-ssf** [comment] 2023-06-19 17:50
> > @chlenc @lzhabo, could I have more context about the transaction that executes the `cancel order` predicate?
> > This transaction will need to be created manually. I can provide a gist outlining the necessary steps, but to do so, I need a comprehensive understanding of all actions that should occur within this transaction.
> 
> can you tell me specifically what information besides this I can provide? maybe we should call?

@chlenc, thank you for your responses. To create a custom transaction that fits your use case, I need to understand what should be included in the transaction's inputs and outputs. I think I've grasped the intended action, as the code comments have provided very good insights.

From my understanding, this transaction will be sent by the receiver, correct? Is that why you're sending an amount of 0 to the predicate in the code you provided?

If this predicate returns true, will the order be canceled? What are the implications of an order cancellation within this transaction? For example, if the predicate returns true, should we expect some assets owned by the predicate to be transferred back to the receiver in this same transaction?

If my previous assumptions are incorrect, I'd be more than happy to discuss this in a call.

**Comment by chlenc** [comment] 2023-06-19 17:53
@Torres-ssf so, You can find inputs and outputs from logs here 
https://github.com/compolabs/ethglobal-predicate/blob/58ac7ef13faaaf84cddfa7d199fa88be359834c8/tests/local_tests/cancel_order_test.rs#L19

**Comment by chlenc** [comment] 2023-06-19 17:57
@Torres-ssf Also we can have a call today or tomorrow, You are in Brazil timezone, right?

**Comment by Torres-ssf** [comment] 2023-06-21 20:03
@chlenc @lzhabo, I've successfully executed a transaction that uses [your predicate](https://github.com/compolabs/spark-rs/blob/58ac7ef13faaaf84cddfa7d199fa88be359834c8/limit-order-predicate/src/main.sw) to cancel an order. I've written a [detailed Gist](https://gist.github.com/Torres-ssf/f9a0efc6b593f85e3e7a420d0cc420f5) that contains the code I used and also added some explanatory notes.

The `cancel_order` transaction fees can be handled either by Alice or the predicate, and the construction of the transaction varies based on who is responsible for paying the fees.

In my tests, I was able to execute the transaction and return the order amount to Alice's address using your predicate. I am using your [Proxy Contract](https://github.com/compolabs/spark-rs/blob/58ac7ef13faaaf84cddfa7d199fa88be359834c8/proxy-contract/src/main.sw) to send the order amount to the predicate. 

I've used the latest version of the SDK which is `0.45.0`, and utilizes `fuel-core: 0.18.1` and `forc: 0.40.1`.

Please feel free to ask if you have any questions. I am also open to join a meeting to go over the details of this Gist.

**Comment by chlenc** [comment] 2023-06-22 12:16
> @chlenc @lzhabo, I've successfully executed a transaction that uses [your predicate](https://github.com/compolabs/spark-rs/blob/58ac7ef13faaaf84cddfa7d199fa88be359834c8/limit-order-predicate/src/main.sw) to cancel an order. I've written a [detailed Gist](https://gist.github.com/Torres-ssf/f9a0efc6b593f85e3e7a420d0cc420f5) that contains the code I used and also added some explanatory notes.
> 
> The `cancel_order` transaction fees can be handled either by Alice or the predicate, and the construction of the transaction varies based on who is responsible for paying the fees.
> 
> In my tests, I was able to execute the transaction and return the order amount to Alice's address using your predicate. I am using your [Proxy Contract](https://github.com/compolabs/spark-rs/blob/58ac7ef13faaaf84cddfa7d199fa88be359834c8/proxy-contract/src/main.sw) to send the order amount to the predicate.
> 
> I've used the latest version of the SDK which is `0.45.0`, and utilizes `fuel-core: 0.18.1` and `forc: 0.40.1`.
> 
> Please feel free to ask if you have any questions. I am also open to join a meeting to go over the details of this Gist.

Perfect, thanks a lot, will try to play with that

**Comment by chlenc** [comment] 2023-06-22 14:43
> @chlenc @lzhabo, I've successfully executed a transaction that uses [your predicate](https://github.com/compolabs/spark-rs/blob/58ac7ef13faaaf84cddfa7d199fa88be359834c8/limit-order-predicate/src/main.sw) to cancel an order. I've written a [detailed Gist](https://gist.github.com/Torres-ssf/f9a0efc6b593f85e3e7a420d0cc420f5) that contains the code I used and also added some explanatory notes.
> 
> The `cancel_order` transaction fees can be handled either by Alice or the predicate, and the construction of the transaction varies based on who is responsible for paying the fees.
> 
> In my tests, I was able to execute the transaction and return the order amount to Alice's address using your predicate. I am using your [Proxy Contract](https://github.com/compolabs/spark-rs/blob/58ac7ef13faaaf84cddfa7d199fa88be359834c8/proxy-contract/src/main.sw) to send the order amount to the predicate.
> 
> I've used the latest version of the SDK which is `0.45.0`, and utilizes `fuel-core: 0.18.1` and `forc: 0.40.1`.
> 
> Please feel free to ask if you have any questions. I am also open to join a meeting to go over the details of this Gist.

Hi, thanks
I played with this code a bit and on that line
https://gist.github.com/Torres-ssf/f9a0efc6b593f85e3e7a420d0cc420f5#file-cancel_order-ts-L20

I failed with that error
```
/Users/alexey/projects/spark-ts-sdk/node_modules/graphql-request/src/index.ts:441
    throw new ClientError(
          ^
ClientError: Unknown field "chainId" on type "ConsensusParameters".: {"response":{"data":null,"errors":[{"message":"Unknown field \"chainId\" on type \"ConsensusParameters\".","locations":[{"line":33,"column":3}]}],"status":200,"headers":{}},"request":{"query":"query getChain {\n  chain {\n    ...chainInfoFragment\n  }\n}\n\nfragment chainInfoFragment on ChainInfo {\n  name\n  baseChainHeight\n  peerCount\n  consensusParameters {\n    ...consensusParametersFragment\n  }\n  latestBlock {\n    ...blockFragment\n  }\n}\n\nfragment consensusParametersFragment on ConsensusParameters {\n  contractMaxSize\n  maxInputs\n  maxOutputs\n  maxWitnesses\n  maxGasPerTx\n  maxScriptLength\n  maxScriptDataLength\n  maxStorageSlots\n  maxPredicateLength\n  maxPredicateDataLength\n  gasPriceFactor\n  gasPerByte\n  maxMessageDataLength\n  chainId\n}\n\nfragment blockFragment on Block {\n  id\n  header {\n    height\n    time\n  }\n  transactions {\n    id\n  }\n}"}}
    at makeRequest (/Users/alexey/projects/spark-ts-sdk/node_modules/graphql-request/src/index.ts:441:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Provider.getChain (/Users/alexey/projects/spark-ts-sdk/node_modules/@fuel-ts/providers/src/provider.ts:289:23)
    at async Provider.getChainId (/Users/alexey/projects/spark-ts-sdk/node_modules/@fuel-ts/providers/src/provider.ts:296:9) {
  response: {
    data: null,
    errors: [ [Object] ],
    status: 200,
    headers: Headers { [Symbol(map)]: [Object: null prototype] }
  },
  request: {
    query: 'query getChain {\n' +
      '  chain {\n' +
      '    ...chainInfoFragment\n' +
      '  }\n' +
      '}\n' +
      '\n' +
      'fragment chainInfoFragment on ChainInfo {\n' +
      '  name\n' +
      '  baseChainHeight\n' +
      '  peerCount\n' +
      '  consensusParameters {\n' +
      '    ...consensusParametersFragment\n' +
      '  }\n' +
      '  latestBlock {\n' +
      '    ...blockFragment\n' +
      '  }\n' +
      '}\n' +
      '\n' +
      'fragment consensusParametersFragment on ConsensusParameters {\n' +
      '  contractMaxSize\n' +
      '  maxInputs\n' +
      '  maxOutputs\n' +
      '  maxWitnesses\n' +
      '  maxGasPerTx\n' +
      '  maxScriptLength\n' +
      '  maxScriptDataLength\n' +
      '  maxStorageSlots\n' +
      '  maxPredicateLength\n' +
      '  maxPredicateDataLength\n' +
      '  gasPriceFactor\n' +
      '  gasPerByte\n' +
      '  maxMessageDataLength\n' +
      '  chainId\n' +
      '}\n' +
      '\n' +
      'fragment blockFragment on Block {\n' +
      '  id\n' +
      '  header {\n' +
      '    height\n' +
      '    time\n' +
      '  }\n' +
      '  transactions {\n' +
      '    id\n' +
      '  }\n' +
      '}',
    variables: undefined
  }
}
```

Do you have any ideas what it can be?

**Closed** 2023-09-01 16:33 UTC
Labels: New feature, dev-experience
