### ISSUE TITLE
No storage provided

### ISSUE THREAD

**Issue by chappie1998** [FuelLabs/fuels-ts#2513] opened 2024-06-13 13:41 UTC
### What version of fuels-ts are you using?

0.89.1

### Steps to Reproduce

Used default connectors in the next app., getting the error while building the application during deploying. 

### Expected Behavior

the error should not be there

### Actual Behavior
```console
No storage provided

error:- 


Error: No storage provided
    at e.getStorage (/home/chappie/fuelart_app/.next/server/chunks/987.js:23:241993)
    at new e (/home/chappie/fuelart_app/.next/server/chunks/987.js:23:241401)
    at D (/home/chappie/fuelart_app/.next/server/chunks/987.js:23:248250)
    at 8141 (/home/chappie/fuelart_app/.next/server/chunks/672.js:1:2371)
    at t (/home/chappie/fuelart_app/.next/server/webpack-runtime.js:1:142)
    at F (/home/chappie/fuelart_app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:91984)
    at $ (/home/chappie/fuelart_app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:90535)
    at rE (/home/chappie/fuelart_app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:34657)
    at nO (/home/chappie/fuelart_app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:60678)
    at nI (/home/chappie/fuelart_app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:65445)
(node:751587) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
```

**Comment by maschad** [comment] 2024-06-13 13:50
Thanks for raising this issue, it seems to be that you are trying to access the window before it's initialized. Could you provide a link to the next app and steps to reproduce this on the repo?

**Comment by chappie1998** [comment] 2024-06-14 14:08
hey @maschad https://github.com/chappie1998/my-fuel-project/tree/storage-bug I made a dummy repo for bug. you just need to build the repo.

**Comment by LuizAsFight** [comment] 2024-06-17 14:36
this one looks like it's in connector side, instead of sdk @chappie1998 , by any change are you using the `defaultConnectors` and building it in nodejs env?

**Comment by chappie1998** [comment] 2024-06-17 14:38
@LuizAsFight yes

**Comment by maschad** [comment] 2024-06-17 17:25
@chappie1998 I haven't been able to reproduce this error on my side. I've built the project and I have it running at localhost (see the screenshot attached).
<img width="2501" alt="Screenshot 2024-06-17 at 12 20 37 PM" src="https://github.com/FuelLabs/fuels-ts/assets/9755286/2260e336-5563-4871-b908-e49e24a332bf">

Below is my `fuelup show` output for my toolchain
<img width="297" alt="Screenshot 2024-06-17 at 12 23 00 PM" src="https://github.com/FuelLabs/fuels-ts/assets/9755286/b236a501-8d20-4d27-b5ec-e2aef7dd719b">

Could you please provide clear step-by-step instructions on how to reproduce this exact error?

As @LuizAsFight asked are you using `defaultConnectors` to deploy to a node environment? As the `window` would not be available there.

**Comment by LuizAsFight** [comment] 2024-06-18 03:07
we are aware of this problem, should be fixed soon https://github.com/FuelLabs/fuel-connectors/issues/107

**Comment by maschad** [comment] 2024-06-18 03:28
I'll close this issue as it's not directly related to this repo. We can continue tracking it at https://github.com/FuelLabs/fuel-connectors/issues/107

**Closed by maschad** 2024-06-18 03:28 UTC
Labels: awaiting, triage
