### ISSUE TITLE
Remove Call Limit for `multicall` method

### ISSUE THREAD

**Issue by meliksahgurtemel** [FuelLabs/fuels-ts#915] opened 2023-04-20 19:09 UTC
### Motivation

In Rust SDK, there is `MultiContractCallHandler`, which basically adds the calls to a [vec](https://github.com/FuelLabs/fuels-rs/blob/master/packages/fuels-programs/src/contract.rs#L755). However, in TS SDK, the number of calls in a multicall is supported up to [only 5 calls](https://github.com/FuelLabs/fuels-ts/blob/master/packages/program/src/contract-call-script.ts#L28) and it is basically a blocker for devs. It would be much better to have it like in Rust SDK

### Possible implementations

It could be implemented similarly to Rust SDK

**Comment by arboleya** [comment] 2023-04-23 10:26
Duplicate of #625.

**Closed by arboleya** 2023-04-23 10:26 UTC
