### ISSUE TITLE
Make `abi` a mandatory `Predicate` parameter

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#3386] opened 2024-11-12 16:42 UTC
Currently, one can instantiate a `Predicate` without an abi, which is only useful in the narrow case of using it as an `Account` because you don't need the abi for using `Account`-specific methods. However, doing any encoding work necessitates the abi (encoding data, configurables, deploying blob) so we should mandate it. If the user wants to use the predicate as an account, they can always instantiate it as such: `const account = new Account(predicateAddress, provider)`.

**Comment by Dhaiwat10** [comment] 2024-11-13 03:23
This is a duplicate of https://github.com/FuelLabs/fuels-ts/issues/1843

**Comment by petertonysmith94** [comment] 2024-11-13 06:34
> This is a duplicate of #1843

Closed in favour of #1843

**Closed by petertonysmith94** 2024-11-13 06:34 UTC
Labels: chore
