### ISSUE TITLE
library doesn't work well with React-native

### ISSUE THREAD

**Issue by singhparshant** [FuelLabs/fuels-ts#2614] opened 2024-06-24 19:26 UTC
### What version of fuels-ts are you using?

0.90.0

### Steps to Reproduce

Set up a React-native project which uses provider and account modules.

### Expected Behavior

The library should work as expected.

### Actual Behavior

Details in this fuel forum issue:

https://forum.fuel.network/t/fuel-ts-in-react-native/5954/8

**Comment by maschad** [comment] 2024-06-24 20:08
Thanks for reporting this @singhparshant whilst we would love to support React Native, it currently isn't a high priority for us for mainnet. Also, this is a larger effort which needs to be fleshed out in a broader issue which I've done in https://github.com/FuelLabs/fuels-ts/issues/2615

I'm closing this issue since it is a duplicate of that one.

**Closed by maschad** 2024-06-24 20:08 UTC
Labels: bug
