### ISSUE TITLE
Update Provider Transaction Response waitForResult to poll for updates on SubmittedStatus

### ISSUE THREAD

**Issue by camsjams** [FuelLabs/fuels-ts#301] opened 2022-05-27 18:32 UTC
Per #203 there is a todo within [@fuel-ts/providers](https://github.com/FuelLabs/fuels-ts/blob/master/packages/providers/src/transaction-response/transaction-response.ts#L107-L109) to implement GraphQL subscription or some basic polling feature.

**Comment by luizstacio** [comment] 2022-06-15 23:20
This would also require something on the `fuel-core` I think. cc: @Voxelot

**Comment by Dhaiwat10** [comment] 2023-04-03 14:43
This might be a duplicate of #782

**Closed** 2024-01-26 15:06 UTC
Labels: feat
