### ISSUE TITLE
Add validation around `programType` in relevant places

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#2787] opened 2024-07-18 08:53 UTC
https://github.com/FuelLabs/fuel-specs/pull/596 introduced the [`programType`](https://github.com/FuelLabs/fuel-specs/pull/596/files#diff-29c836429beedee654a72c37d1f883c1e5a0084d468e1446c61da13d7f88783dR37) property on the abi. Once this is part of `forc` outputs, we can use it to validate ABIs in the constructors of `Contract`, `ContractFactory`, `Predicate`, `Script`, and anywhere else that it's used.

**Comment by arboleya** [comment] 2024-07-18 09:51
Duplicate of:
 - https://github.com/FuelLabs/fuels-ts/issues/989

**Comment by arboleya** [comment] 2024-07-18 09:52
@nedsalk Please, feel free to add extra notes to the original issue's description.

**Closed by arboleya** 2024-07-18 09:51 UTC
Labels: feat, blocked, p2
