### ISSUE TITLE
The revert reason-parsing logic throws when a tx simulation reverts

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#1236] opened 2023-09-04 02:19 UTC
This has been reported [here](https://forum.fuel.network/t/get-error-when-try-to-add-contract-to-other-contract-call/3034) and [here](https://forum.fuel.network/t/typeerror-cannot-read-properties-of-undefined-reading-status/3047/3).

<details>
  <summary>Screenshot</summary>
  
![error](https://github.com/FuelLabs/fuels-ts/assets/39617427/e3fa4208-250c-4091-a6ce-2558178b6ac3)

</details>

This snippet should simulate the TX and return the correct revert reason, assuming the tx is expected to revert.

```ts
await contract.functions.my_function().simualte()
```

The error is thrown here: https://github.com/FuelLabs/fuels-ts/blob/f1bb197bbe448ae0e5f75ae7902364e2a7475826/packages/program/src/errors.ts#L17

**Comment by cold-briu** [comment] 2023-09-04 18:47
Another [incidence](https://forum.fuel.network/t/typeerror-cannot-read-properties-of-undefined-reading-status/3047)

**Comment by arboleya** [comment] 2023-09-05 23:02
Likely a duplicate of #1237.

**Comment by Torres-ssf** [comment] 2023-09-12 17:43
Most likely is the same problem that we have on https://github.com/FuelLabs/fuels-ts/issues/1245

**Comment by Torres-ssf** [comment] 2023-09-12 17:50
Closing in favor of https://github.com/FuelLabs/fuels-ts/issues/1245

**Closed by Torres-ssf** 2023-09-12 17:50 UTC
Labels: bug
