### ISSUE TITLE
When deploying the contract using typescript code, the variables are not initialized, but there is no problem using npx fuels deploy

### ISSUE THREAD

**Issue by cherideal** [FuelLabs/fuels-ts#2484] opened 2024-06-09 05:26 UTC
### What version of fuels-ts are you using?

0.89.1

### Steps to Reproduce

https://github.com/bookswapxyz/fuel-swap/blob/main/AMM/exchange-contract/src/main.sw

    storage {
        liquidity_pool_supply: u64 = 0
    }

    #[storage(read)]
    fn test1() {
        log(storage.liquidity_pool_supply.read());
    }

    #[storage(read)]
    fn test2() {
        log(storage.liquidity_pool_supply.try_read());
    }

deploy the exchange-contract with `yarn start --task=createPool`, and then check it with `yarn start --task=test1, yarn start --task=test2`, 

### Expected Behavior

`yarn start --task=test1, yarn start --task=test2` not return exception

### Actual Behavior

```
yarn start --task=test1
```
 returns exception like this:

```console
  return new FuelError(ErrorCode.SCRIPT_REVERTED, errorMessage, metadata);
         ^
_FuelError: The transaction reverted with an unknown reason: 0
    at extractTxError (/home/cherideal/work/ShareWin/fuel-swap/Play-Ground/node_modules/@fuel-ts/account/src/providers/utils/extract-tx-error.ts:128:10)
    at _Provider.extractDryRunError (/home/cherideal/work/ShareWin/fuel-swap/Play-Ground/node_modules/@fuel-ts/account/src/providers/provider.ts:1803:12)
    at _Provider.getTransactionCost (/home/cherideal/work/ShareWin/fuel-swap/Play-Ground/node_modules/@fuel-ts/account/src/providers/provider.ts:1176:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FunctionInvocationScope.getTransactionCost (/home/cherideal/work/ShareWin/fuel-swap/Play-Ground/node_modules/@fuel-ts/program/src/functions/base-invocation-scope.ts:230:20)
    at async FunctionInvocationScope.fundWithRequiredCoins (/home/cherideal/work/ShareWin/fuel-swap/Play-Ground/node_modules/@fuel-ts/program/src/functions/base-invocation-scope.ts:248:20)
    at async FunctionInvocationScope.simulate (/home/cherideal/work/ShareWin/fuel-swap/Play-Ground/node_modules/@fuel-ts/program/src/functions/base-invocation-scope.ts:396:32) {
  VERSIONS: { FORC: '0.60.0', FUEL_CORE: '0.27.0', FUELS: '0.89.1' },
  metadata: {
    logs: [],
    receipts: [ [Object], [Object], [Object] ],
    panic: false,
    revert: true,
    reason: 'unknown'
  },
  code: 'script-reverted'
}
```

**Comment by maschad** [comment] 2024-06-17 18:05
Hey @cherideal I suspect this may be because the pool wasn't initialized, after running

**Comment by maschad** [comment] 2024-06-17 18:08
Hey @cherideal I suspect this may be because the pool was not initialized, after running

```
yarn start --task=initPool
```

then running 

```
yarn start --task=test1
```

I got the following output

```console
fuel19ztwgeul8yzffsr0df0me8kk8vtr5xpnwlkup79aksv8m47m9h0qdxlfru
0xf8f8b6283d7fa5b672b530cbb84fcccb4ff8dc40f8176ef4544ddb1f1952ad07 1929679
test1 done
0x580085ecb00ce878a662d19582a5d40cbe4417184f2514ed427c937ce4f50781 test USD tUSD 6
0x299ea939953a56ab887dc663140b7b65da4be47851eb5f216d5201290cdae30d test BTC tBTC 10
{
  tokenContract: '0xf1ea11be20f8d6d7a30ff69f21bffc1a95910e0459b03fbdd5c5070f4f48f82d',
  tokens: [
    {
      assetId: '0x580085ecb00ce878a662d19582a5d40cbe4417184f2514ed427c937ce4f50781',
      subId: '0x0000000000000000000000000000000000000000000000000000000000000000',
      name: 'test USD',
      symbol: 'tUSD',
      decimals: 6
    },
    {
      assetId: '0x299ea939953a56ab887dc663140b7b65da4be47851eb5f216d5201290cdae30d',
      subId: '0x0000000000000000000000000000000000000000000000000000000000000001',
      name: 'test BTC',
      symbol: 'tBTC',
      decimals: 10
    }
  ],
  ammContract: '0xe00f7e7f0508ef31649b828bdfc1518c38e1b9ae09e04cb9681cfe6ba66a66de',
  pools: {
    '0x580085ecb00ce878a662d19582a5d40cbe4417184f2514ed427c937ce4f50781': {
      '0x299ea939953a56ab887dc663140b7b65da4be47851eb5f216d5201290cdae30d': '0x5600472e368e0934a39d5c2c25db0b56152939265a9181e6a91bf8fc3d68d04a'
    },
    '0x299ea939953a56ab887dc663140b7b65da4be47851eb5f216d5201290cdae30d': {
      '0x580085ecb00ce878a662d19582a5d40cbe4417184f2514ed427c937ce4f50781': '0x5600472e368e0934a39d5c2c25db0b56152939265a9181e6a91bf8fc3d68d04a'
    }
  }
}
✨  Done in 4.89s.
```

and then 

``` 
yarn start --task=test2
```

```console
❯ yarn start --task=test2
yarn run v1.22.19
warning ../../../package.json: No license field
$ ts-node src/index.ts --task=test2
The Fuel Node that you are trying to connect to is using fuel-core version 0.29.0,
which is not supported by the version of the TS SDK that you are using.
Things may not work as expected.
Supported fuel-core version: 0.27.0.
fuel19ztwgeul8yzffsr0df0me8kk8vtr5xpnwlkup79aksv8m47m9h0qdxlfru
0xf8f8b6283d7fa5b672b530cbb84fcccb4ff8dc40f8176ef4544ddb1f1952ad07 1929679
test2 done
0x580085ecb00ce878a662d19582a5d40cbe4417184f2514ed427c937ce4f50781 test USD tUSD 6
0x299ea939953a56ab887dc663140b7b65da4be47851eb5f216d5201290cdae30d test BTC tBTC 10
{
  tokenContract: '0xf1ea11be20f8d6d7a30ff69f21bffc1a95910e0459b03fbdd5c5070f4f48f82d',
  tokens: [
    {
      assetId: '0x580085ecb00ce878a662d19582a5d40cbe4417184f2514ed427c937ce4f50781',
      subId: '0x0000000000000000000000000000000000000000000000000000000000000000',
      name: 'test USD',
      symbol: 'tUSD',
      decimals: 6
    },
    {
      assetId: '0x299ea939953a56ab887dc663140b7b65da4be47851eb5f216d5201290cdae30d',
      subId: '0x0000000000000000000000000000000000000000000000000000000000000001',
      name: 'test BTC',
      symbol: 'tBTC',
      decimals: 10
    }
  ],
  ammContract: '0xe00f7e7f0508ef31649b828bdfc1518c38e1b9ae09e04cb9681cfe6ba66a66de',
  pools: {
    '0x580085ecb00ce878a662d19582a5d40cbe4417184f2514ed427c937ce4f50781': {
      '0x299ea939953a56ab887dc663140b7b65da4be47851eb5f216d5201290cdae30d': '0x5600472e368e0934a39d5c2c25db0b56152939265a9181e6a91bf8fc3d68d04a'
    },
    '0x299ea939953a56ab887dc663140b7b65da4be47851eb5f216d5201290cdae30d': {
      '0x580085ecb00ce878a662d19582a5d40cbe4417184f2514ed427c937ce4f50781': '0x5600472e368e0934a39d5c2c25db0b56152939265a9181e6a91bf8fc3d68d04a'
    }
  }
}
```

Could you retry the commands and then let me know if this solves your issue?

**Comment by cherideal** [comment] 2024-06-18 05:56
yarn start --task=initPool is used to manually initialize variables, but the problem now is that the variables are not initialized when they are defined.

**Comment by maschad** [comment] 2024-06-18 19:42
> yarn start --task=initPool is used to manually initialize variables, but the problem now is that the variables are not initialized when they are defined.

My bad thanks for the clarification, the issue is that you weren't passing the [`storageSlots`](https://github.com/FuelLabs/fuels-ts/blob/master/packages/contract/src/contract-factory.ts#L19) as an option when you were [deploying the pool contract](https://github.com/bookswapxyz/fuel-swap/blob/main/Play-Ground/src/ammHelper.ts#L36-L53) in the [`createPool`](https://github.com/bookswapxyz/fuel-swap/blob/main/Play-Ground/src/index.ts#L120) task.

I've applied the fix [here](https://github.com/maschad/fuel-swap/blob/mc/simulate-error/Play-Ground/src/ammHelper.ts#L36-L55) and it works for me. See the code snippet below:

```ts
export const deploy_pool_contract = async (wallet: Account, assetIdA: string, assetIdB: string) => {

    const bytecodeDir = join(__dirname, '../../AMM/exchange-contract/out/debug/exchange-contract.bin')

	// Get the storage slot directory
    const storageSlotsDir = join(__dirname, '../../AMM/exchange-contract/out/debug/exchange-contract-storage_slots.json')

    const bytecode = readFileSync(bytecodeDir)
	
    // Parse the Storage slot JSON object
    const storageSlots = JSON.parse(readFileSync(storageSlotsDir, 'utf-8'))

    const factory = new ContractFactory(bytecode, ExchangeContractAbi__factory.abi, wallet)

    // Ensure it's passed to the deployContract function call
    let contractAbi = await factory.deployContract({ storageSlots })

    return contractAbi as ExchangeContractAbi
}
```

Does this solve your issue?

**Comment by cherideal** [comment] 2024-06-19 00:12
This solves my problem, but what is the purpose of the initialization here?
storage {
    liquidity_pool_supply: u64 = 0
}

**Comment by maschad** [comment] 2024-06-19 16:45
> This solves my problem, but what is the purpose of the initialization here? storage { liquidity_pool_supply: u64 = 0 }

Those said values that where initialized in a storage slot also need to be deployed with the smart contract in order for the VM to allocate the storage blocks. That's the purpose of the custom storage slots. You can read more about storage [here](https://docs.fuel.network/docs/sway/blockchain-development/storage/)

I'm going to close this issue since the initial problem has been addressed. Feel free to open a [discussion](https://github.com/FuelLabs/fuels-ts/discussions/new/choose) or [forum post](https://forum.fuel.network/) if you have any more questions about storage.

**Closed by maschad** 2024-06-19 16:45 UTC
Labels: awaiting, triage
