### ISSUE TITLE
Command `fuels dev` hangs on generating types

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#1886] opened 2024-03-18 13:49 UTC
Incoming via:

 - https://github.com/FuelLabs/fuels-ts/discussions/1881

Generating types hangs in fuels dev, had to restart command.

![error](https://github.com/FuelLabs/fuels-ts/assets/26660/7799b697-11eb-4aeb-9b61-e1e632e5ddeb)

Possibly related:
 - https://github.com/FuelLabs/fuels-ts/issues/1951

> cc @matt-user @Dhaiwat10

**Comment by danielbate** [comment] 2024-08-15 10:59
Any intel to share @nedsalk or did you just un-assign as you aren't working on it?

**Comment by danielbate** [comment] 2024-12-02 09:33
@matt-user @Dhaiwat10 @FuelLabs/sdk-ts does anyone have a consistent reproduction of this? Keep getting caught because I can't consistently reproduce it.

**Comment by Dhaiwat10** [comment] 2024-12-09 08:46
@danielbate I am no longer being able to reproduce this either. If I come across it, I'll re-open this issue. Closing for now

**Closed** 2024-12-09 08:46 UTC
Labels: bug, awaiting

**Comment by Dhaiwat10** [comment] 2024-12-26 12:50
I have found a reliable repro:

Whenever there is a compilation error in one of your Sway programs, `fuels dev` tends to hang. Re-opening this.

**Comment by Dhaiwat10** [comment] 2024-12-26 12:52
I am working on a fix
