### ISSUE TITLE
EC is not a constructor

### ISSUE THREAD

**Issue by simple-YoungBadBoy** [FuelLabs/fuels-ts#1348] opened 2023-10-15 04:51 UTC
### What version of fuels-ts are you using?

0.62.0

### Steps to Reproduce

just npm i fuels
running 
`
import { Wallet } from "fuels"

// Random Wallet
console.log(Wallet.generate())
`

got error:
file:///Users/simpboy/code/fuel-study/node_modules/@fuel-ts/signer/dist/index.mjs:10
  return new EC("secp256k1");
         ^

TypeError: EC is not a constructor
    at getCurve (file:///Users/simpboy/code/fuel-study/node_modules/@fuel-ts/signer/dist/index.mjs:10:10)
    at new Signer (file:///Users/simpboy/code/fuel-study/node_modules/@fuel-ts/signer/dist/index.mjs:30:21)
    at new BaseWalletUnlocked (file:///Users/simpboy/code/fuel-study/node_modules/@fuel-ts/wallet/dist/index.mjs:436:20)
    at new WalletUnlocked (file:///Users/simpboy/code/fuel-study/node_modules/@fuel-ts/wallet/dist/index.mjs:545:22)
    at Wallet.generate (file:///Users/simpboy/code/fuel-study/node_modules/@fuel-ts/wallet/dist/index.mjs:563:12)
    at file:///Users/simpboy/code/fuel-study/index.js:4:20
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.16.0

### Expected Behavior

can usr Wallet.generate() 

### Actual Behavior

error:

file:///Users/simpboy/code/fuel-study/node_modules/@fuel-ts/signer/dist/index.mjs:10
  return new EC("secp256k1");
         ^

TypeError: EC is not a constructor
    at getCurve (file:///Users/simpboy/code/fuel-study/node_modules/@fuel-ts/signer/dist/index.mjs:10:10)
    at new Signer (file:///Users/simpboy/code/fuel-study/node_modules/@fuel-ts/signer/dist/index.mjs:30:21)
    at new BaseWalletUnlocked (file:///Users/simpboy/code/fuel-study/node_modules/@fuel-ts/wallet/dist/index.mjs:436:20)
    at new WalletUnlocked (file:///Users/simpboy/code/fuel-study/node_modules/@fuel-ts/wallet/dist/index.mjs:545:22)
    at Wallet.generate (file:///Users/simpboy/code/fuel-study/node_modules/@fuel-ts/wallet/dist/index.mjs:563:12)
    at file:///Users/simpboy/code/fuel-study/index.js:4:20
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.16.0

**Comment by haardikk21** [comment] 2023-10-15 22:31
Ran into the same issue - it seems like a weird NodeJS ESM/CJS/UMD problem

My setup is basically Next.js 13.5.4 with NodeJS 18.18.0 

Funnily enough, I have `elliptic` as a dependency of my own in my code - and doing basically the exact same thing that Fuel is doing within their library - something like:

```
import * as elliptic from "elliptic"

// later

const EC = new elliptic.ec("secp256k1")
```

works perfectly fine for me

But, adding `fuels` as a dep to my project - I get the same error

Adding a console log for their `elliptic` import gives me a `default` object:

```
{
  elliptic: [Module: null prototype] {
    default: {
      version: '6.5.4',
      utils: [Object],
      rand: [Function],
      curve: [Object],
      curves: [Object],
      ec: [Function: EC],
      eddsa: [Function: EDDSA]
    }
  }
}
```

Therefore, the fix (in our case) would be to change this line - https://github.com/FuelLabs/fuels-ts/blob/master/packages/signer/src/signer.ts#L13 - to something like:

```ts
const EC = elliptic.default.ec
```

a more global fix that would (I think) work for everyone would be something like this:

```ts
const EC = elliptic.default ? elliptic.default.ec : elliptic.ec
```

I don't want to spend my time digging deep into webpack transpilation issues and god knows I hate the whole CJS/ESM incompatibility issue - but I believe the above will work. 

I'm sure there's some webpack/tsconfig or some setting we can make on our end too to get this to work, because I tried on StackBlitz and a fresh `app` dir next.js project with the latest `fuels` SDK installed doesn't face the same issue - but my set up does, and I'd rather not spend the time currently trying to diagnose which exact webpack or TSConfig setting in my codebase is causing it to blow up like this

**Comment by haardikk21** [comment] 2023-10-15 22:56
Quick update: if you're using Next.js, I was able to get around this by adding `fuels` to the Next.js config `transpilePackages` array

**Comment by Dhaiwat10** [comment] 2023-10-17 17:49
@haardikk21 @simple-YoungBadBoy thanks for the bug, would you guys be able to share a repo so that I can reproduce the bug?

**Comment by haardikk21** [comment] 2023-10-17 18:20
I'll try to send a reproducible example ASAP - it has likely smth to do with webpack and/or ts config

**Comment by danielbate** [comment] 2023-12-08 16:47
Closing as no reproducible example has been provided.

**Closed by danielbate** 2023-12-08 16:47 UTC
Labels: bug
