### ISSUE TITLE
Fix flaky `TransactionResponse` test

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#2318] opened 2024-05-16 13:14 UTC
https://github.com/FuelLabs/fuels-ts/actions/runs/9112255896/job/25051134389?pr=2291#step:5:709

![image](https://github.com/FuelLabs/fuels-ts/assets/17943891/d964b17f-1ab8-4f11-b031-5acb03ac6988)

We're currently skipping this test as it's failing across the board and breaking our workflows.

**Comment by arboleya** [comment] 2024-05-20 10:31
@nedsalk Should this go in https://github.com/FuelLabs/fuels-ts/issues/1755 instead?

**Comment by nedsalk** [comment] 2024-05-21 13:05
@arboleya it can be put there, I guess. I put it separately because I wanted to track it in isolation.

**Comment by arboleya** [comment] 2024-06-10 19:55
Is this a duplicate of the below? cc @maschad 
 - https://github.com/FuelLabs/fuels-ts/issues/2200

**Comment by maschad** [comment] 2024-06-10 20:00
Looks so @arboleya I think the original issue got closed by https://github.com/FuelLabs/fuels-ts/pull/2268 but it has resurfaced and thus #2200 was re-opened. Closing this as a duplicate.

**Closed by maschad** 2024-06-10 20:00 UTC
Labels: bug, p0
