### ISSUE TITLE
Support React Native

### ISSUE THREAD

**Issue by maschad** [FuelLabs/fuels-ts#2615] opened 2024-06-24 20:06 UTC
We'd love to officially support running on React Native, as some of our consumers have tried to use it (see https://forum.fuel.network/t/fuel-ts-in-react-native/5954/8)

The requirements for this would be:

- The test suite running in CI that builds a basic react native app using [metro](https://developerayo.github.io/metro/en/)
- Lightweight - e.g. the developer should not have to install extra applications or sign EULAs if possible
There's been some preliminary support added to aegir for running tests under Android but I'm not sure what the current state of the art is in automated testing.

A preliminary pass might just be to get a simple demo react-native app running libp2p working. This might involve a list of required changes to modules to polyfill or replace APIs that do not exist/are buggy/incomplete in React Native.

If it helps to reduce the scope, perhaps a stand-alone repo could be tackled first to prove it out instead of the fuel-ts monorepo.

**Comment by nedsalk** [comment] 2024-06-26 11:20
Related (duplicate?): 
- #2570

**Comment by arboleya** [comment] 2024-08-08 18:58
This looks like a duplicate of:
 - https://github.com/FuelLabs/fuels-ts/issues/2570

Can we close this as such?

**Closed** 2024-08-08 19:14 UTC
Labels: feat, good first issue
