### ISSUE TITLE
function getTransactionCost return wrong gas amount 

### ISSUE THREAD

**Issue by nadiia-balaian** [FuelLabs/fuels-ts#2212] opened 2024-04-30 14:31 UTC
### What version of fuels-ts are you using?

82

### Steps to Reproduce

call getTransactionCost and check what this function returns

### Expected Behavior

getTransactionCost returns valid amount of gas

### Actual Behavior

when I'm trying to make transaction and make request to calculate gas for it getTransactionCost, I got value that is not enough to send transaction 
when I try to send transaction with amount from the getTransactionCost I got error OutOfGas 

so we fixed this behaviour on our side with simple workaround  - we multiple amount from getTransactionCost for 2

**Comment by nadiia-balaian** [comment] 2024-05-02 21:32
> Hello @nadiia-balaian . Sorry about this error.
> 
> Could you provide us with some code snippets and more context on how this error occurred?
> 
> It would help a lot if we could replicate the exact scenario in which this error is happening on your side (executing the same contract call).


Hello @Torres-ssf 
So we tested later the same code and we found out that problem is not in this exact function.
![photo_2024-05-01_11-19-42](https://github.com/FuelLabs/fuels-ts/assets/109521832/5276ef8c-1a03-4ea1-bc68-c1d1290a5ea9).

**Comment by Torres-ssf** [comment] 2024-05-03 11:52
@nadiia-balaian It seems that the given print refers to the Rust SDK.

Are you experiencing the same error (OutOfGas) while using the TS SDK when calling the function `open_order` ?

**Comment by Torres-ssf** [comment] 2024-06-07 15:42
Closing this as I could not reproduce this error while executing contract calls on beta-5.

**Closed by Torres-ssf** 2024-06-07 15:42 UTC
Labels: bug
