### ISSUE TITLE
Incorrect logs decoding of errors in cross-contract calls

### ISSUE THREAD

**Issue by theausicist** [FuelLabs/fuels-ts#2403] opened 2024-05-28 12:38 UTC
### What version of fuels-ts are you using?

0.60.0

### Steps to Reproduce

Contract `B` calls a method in contract `A` which fails an invariant. Both contracts have error-enum structs like so:

```rust
// contract A
pub enum Error {
    ContrABlah1: (),
    ContrABlah2: ()
}

// contract B
pub enum Error {
    ContrBBlah1: (),
    ContrBBlah2: ()
}
```

invariant in method in contract `A` fails:
```rust
// invariant in method in contract A
require(false, Error::ContrABlah2);
```

if I do the following:
```rust
// fn in contract B
contr_A.call_fn_that_fails_invariant();
```

the decoded logs in the TS SDK show that the decoded error is: `ContrBBlah2` (even though this wasn't the error message). Through tests, I have determined that if an error of index `i` in the enum definition as above in contract `A` is the failed message, the error of index `i` in the enum definition of contract `B` will be the one displayed. 

Minimal example: https://gist.github.com/theausicist/82341f40a2a950ce458f4daa51cb01d2

Expected error message in decoded logs: `CaleeError5`
Actual error message in decoded logs:       `CallerError6940`

This has been a bug in all the earlier versions of the TS SDK. I haven't tested this for the Rust SDK yet. 

[Link to full forum post for this issue](https://forum.fuel.network/t/incorrect-logs-decoding-of-errors-in-cross-contract-calls)

### Expected Behavior

In [minimal example](https://gist.github.com/theausicist/82341f40a2a950ce458f4daa51cb01d2), expected error: `CalleeError5`

### Actual Behavior

Actual error: `CallerError6940`

**Comment by theausicist** [comment] 2024-05-28 12:38
the exact error trace is:

```bash
 FuelError: The transaction reverted because a "require" statement has thrown "CallerError6940".
      at extractTxError (node_modules/@fuel-ts/account/src/providers/transaction-request/helpers.ts:43:5)
      at _Provider.extractDryRunError (node_modules/@fuel-ts/account/src/providers/provider.ts:1725:11)
      at _Provider.getTransactionCost (node_modules/@fuel-ts/account/src/providers/provider.ts:1136:7)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at FunctionInvocationScope.getTransactionCost (node_modules/@fuel-ts/program/src/functions/base-invocation-scope.ts:239:6)
      at FunctionInvocationScope.fundWithRequiredCoins (node_modules/@fuel-ts/program/src/functions/base-invocation-scope.ts:261:7)
      at FunctionInvocationScope.call (node_modules/@fuel-ts/program/src/functions/base-invocation-scope.ts:360:12)
```

TS SDK version: `fuels v0.88.0`

It appears that the `functionInvocationScopes` in `BaseInvocationScopes` doesn't include the `abis` of contracts other than the calling contract 

[this line](https://github.com/FuelLabs/fuels-ts/blob/80e0c2361306ffaeb43f35a7b3db4f47706a4f9c/packages/program/src/functions/base-invocation-scope.ts#L200) is where the `main` and `otherContractsAbis` abis are grabbed:
```rust
this.transactionRequest.abis = getAbisFromAllCalls(this.functionInvocationScopes);

// value of this.transactionRequest.abis.otherContractsAbis is {}
```

Here's where the [logs are decoded](https://github.com/FuelLabs/fuels-ts/blob/80e0c2361306ffaeb43f35a7b3db4f47706a4f9c/packages/account/src/providers/transaction-response/getDecodedLogs.ts#L31):

```rust
const interfaceToUse = new Interface(externalAbis[receipt.id] || mainAbi);

// since externalAbis is {}, it always defaults to "mainAbi"

```

**Comment by theausicist** [comment] 2024-05-28 12:39
I fixed this by using `.addContracts` to the function scope before calling the contract like so:
```typescript
// In TS
await caller.functions.call_callee_that_fails(toContract(callee)).addContracts([callee]).call()

// yields the correct error: CalleeError5
```

this is a bug, no doubt. I *shouldn't* have to use `.addContracts` for Fuel to be able to figure out where the error originated from.

**Comment by Torres-ssf** [comment] 2024-05-29 13:28
@theausicist we are deeply sorry about this issue. We also appreciate you letting us about this and taking the time to create a minimal example to reproduce the error. Thanks 🙏 

I am already investigating the problem and will report my findings here later.

**Comment by Torres-ssf** [comment] 2024-05-29 16:05
@theausicist I've successfully reproduced your example at my end.

The issue arises because when `addContracts` is not called, the ABI from the `callee` contract is not included in the contract call operation. Consequently, it won't be possible to decode its logs later on.

## Understanding the problem

When creating a script transaction that will execute a contract call, we must add an [InputContract](https://specs.fuel.network/master/tx-format/input.html#inputcontract) and an [OutputContract](https://specs.fuel.network/master/tx-format/output.html#outputcontract), for the specific contract to the list of inputs and outputs for the transaction.

If this contract function will eventually call another contract, we also need to add an `InputContract` and `OutputContract` for that second contract to the transaction inputs and outputs.

Failing to do so will result in the transaction failing.

This is why the `addContracts` method exists: to add the inputs and outputs from other called contracts, as well as their [ABIs](https://github.com/FuelLabs/fuels-ts/blob/fcf2ea55f89abf45d3a9b6d677a22ddec98a1bbf/packages/program/src/functions/base-invocation-scope.ts#L300).

## Why Doesn't Your Contract Call Fail?

The reason your transaction doesn't fail when you call `call_callee_that_fails` from the `caller` contract without using `addContracts` is that the TS SDK includes code to check if contract information is missing.

This check happens [here](https://github.com/FuelLabs/fuels-ts/blob/fcf2ea55f89abf45d3a9b6d677a22ddec98a1bbf/packages/account/src/providers/provider.ts#L816). The method executes a dry run and validates the returning receipts. If it detects that the dry run failed due to missing contract input and output, it [adds](https://github.com/FuelLabs/fuels-ts/blob/fcf2ea55f89abf45d3a9b6d677a22ddec98a1bbf/packages/account/src/providers/provider.ts#L853) this missing data. This is possible because the returned receipt contains the ID of the missing contract. The code then executes another dry run to validate if the problem is solved.

By adding the input and output of the missing contract on the fly, the SDK allows the call to `call_callee_that_fails` to work without explicitly using `addContracts` to add the `callee` input and output to the transaction.

However, the ABI from the `callee` contract is not added to the contract call operation. This limitation exists because there is no way to retrieve an ABI for a given deployed contract ID.

## Why the wrong error is being logged? 

Typically, if a contract's ABI is missing and the contract throws an error or logs some data, it won't be possible for the [getDecodedLogs](https://github.com/FuelLabs/fuels-ts/blob/80e0c2361306ffaeb43f35a7b3db4f47706a4f9c/packages/account/src/providers/transaction-response/getDecodedLogs.ts#L8) helper to decode the log properly. The `logId` will not be found in the original contract ABI, resulting in an error. This situation is described [in this issue](https://github.com/FuelLabs/fuels-ts/issues/1782).

In your case, no error is thrown when decoding the log because, and this is puzzling, both contracts' ABIs have the exact same `logId` value:

Caller ABI:
<img width="320" alt="Screenshot 2024-05-29 at 12 14 38" src="https://github.com/FuelLabs/fuels-ts/assets/30977845/317cc6b6-76b7-45bf-bb25-5374858f31fa">

Callee ABI:
<img width="325" alt="Screenshot 2024-05-29 at 12 15 46" src="https://github.com/FuelLabs/fuels-ts/assets/30977845/933a5bda-2bc9-45b4-8119-327cbd87d7e2">

Since the same `logId` is present in both ABIs, the code can [decode the log](https://github.com/FuelLabs/fuels-ts/blob/fcf2ea55f89abf45d3a9b6d677a22ddec98a1bbf/packages/abi-coder/src/Interface.ts#L78) properly, even though the correct ABI is not present when decoding the logs.

## Solution

Because it is not possible to retrieve a contract's ABI using just its deployed ID, you must always use `addContracts` to add all external contracts' ABIs to the contract call operation. This ensures that the SDK can always decode logs correctly.

**Comment by jasmcaus** [comment] 2024-05-31 14:49
Thanks @Torres-ssf for the detailed analysis. I did figure out the `.addContracts` call and added it to my notes above as well. I suppose if it would be trivial to assume that it'd be rather difficult to decode errors in cross-contracts calls without the need for the `.addContracts` call due to the nature of the Fuel network and its UTXO-based model?

**Comment by theausicist** [comment] 2024-05-31 14:49
Thanks @Torres-ssf for the detailed analysis. I did figure out the `.addContracts` call and added it to my notes above as well. I suppose if it would be trivial to assume that it'd be rather difficult to decode errors in cross-contracts calls without the need for the `.addContracts` call due to the nature of the Fuel network and its UTXO-based model?

**Comment by Torres-ssf** [comment] 2024-06-12 18:50
@theausicist I reckon you are right. 

The nature of UTXO-based systems can indeed add layers of complexity when dealing with cross-contract interactions and error handling.

I am closing this issue as this is not a problem/bug on the TS SDK side.

**Closed by Torres-ssf** 2024-06-12 18:50 UTC
Labels: bug, p2
