### ISSUE TITLE
Error for decode erros in contract

### ISSUE THREAD

**Issue by luisburigo** [FuelLabs/fuels-ts#1782] opened 2024-02-20 16:40 UTC
### What version of fuels-ts are you using?

0.73.0

### Steps to Reproduce

1.  Create two contracts: 
```sway
abi ContractB {
    #[storage(read)]
    fn method();
}

storage {
    initialized: bool = true, // the value 'true' is to reproduce the error
}

impl ContractB for Contract {
    #[storage(read)]
    fn method() {
       let initalized = storage.initialized.try_read().unwrap_or(false);
       require(!initalized, ContractBError::AlreadyInitialized);
    }
}
```

```sway
abi ContractA {
    fn method(contract_b_id: ContractId);
}

impl ContractA for Contract {
    fn method(contract_b_id: ContractId) {
       let contract_b = abi(ContractB, contract_b_id.into());
       contract_b.method();
    }
}
```

2. Execute the **ContractA** method in **TS**:
```ts
const contractAAbi = ContractAAbi__factory.connect(contractA, wallet);
const result = await contractAAbi.functions.method({
    value: contractB
}).txParams({
    gasPrice: 1,
    gasLimit: 1_000_000,
}).call();
```

### Expected Behavior

The error from `require` in contract:
```shell
return new RequireRevertError(receipt, reason);
             ^
RequireRevertError: The script reverted with reason RequireFailed
```

### Actual Behavior

It triggers the error from `@fuel-ts/abi-coder` instead of triggering the error from the contract.
```bash
throw new FuelError(ErrorCode.ELEMENT_NOT_FOUND, 'Element not found in the array.');
          ^
_FuelError: Element not found in the array.
```

On my case the application that is calling the contract only has knowledge of the contract A and not contract B.

**Comment by luisburigo** [comment] 2024-02-20 16:42
Repository to reproduce the error: [https://github.com/luisburigo/fuel-ts-issue.git](https://github.com/luisburigo/fuel-ts-issue.git)

**Comment by luisburigo** [comment] 2024-02-20 16:59
I debugged the code and found the error in this function:
https://github.com/FuelLabs/fuels-ts/blob/116d642e553784159f29c72989a24cd50aa5c73b/packages/account/src/providers/transaction-response/getDecodedLogs.ts#L8-L22

**Comment by petertonysmith94** [comment] 2024-02-21 10:21
Hey @luisburigo, hope you are well.

I have been playing around with your example (thank you btw), not 100% on the root cause just yet. I did find a potential workaround (hopefully it can unblock you). 

```sway
abi ContractA {
  fn method(contract_b_id: ContractId);
}

impl ContractA for Contract {
  fn method(contract_b_id: ContractId) {
    let contract_b = abi(ContractB, contract_b_id.into());
    let result = contract_b.method();
  }
}
```

With the expected result of:
```text
return new RequireRevertError(receipt, reason);
             ^
RequireRevertError: The script reverted with reason RequireFailed
```

**Comment by arboleya** [comment] 2024-02-21 10:38
The issue is that we need the ABI of all contracts before being able to decode their logs. One suggested solution would be to, in case the ABI is missing and we can't decode logs, to just print a _warning_ and move on instead of throwing.

This is subject to further analysis, of course.

**Comment by luisburigo** [comment] 2024-02-22 18:15
Hey, @petertonysmith94 @arboleya thanks for the response.

This code in the description is just an example. In my contracts, I use the correct abi.

In this repo https://github.com/luisburigo/fuel-ts-issue there is an example of this bug.

**Comment by nedsalk** [comment] 2024-02-23 15:27
@luisburigo I just took a look at your code and you didn't add contract B into the call so the library doesn't know how to decode it. You should do this:
```ts
    const contractAAbi = ContractAAbi__factory.connect(contractA, wallet);
    const contractBAbi = ContractBAbi__factory.connect(contractB, wallet);
    const result = await contractAAbi.functions.method({
        value: contractB
    })
    .addContracts([contractBAbi]) //  <------- this was missing
    .txParams({
        gasPrice: 1,
        gasLimit: 1_000_000,
    })
```

**Comment by petertonysmith94** [comment] 2024-02-25 13:47
> @luisburigo I just took a look at your code and you didn't add contract B into the call so the library doesn't know how to decode it. You should do this:
> 
> ```ts
>     const contractAAbi = ContractAAbi__factory.connect(contractA, wallet);
>     const contractBAbi = ContractBAbi__factory.connect(contractB, wallet);
>     const result = await contractAAbi.functions.method({
>         value: contractB
>     })
>     .addContracts([contractBAbi]) //  <------- this was missing
>     .txParams({
>         gasPrice: 1,
>         gasLimit: 1_000_000,
>     })
> ```

Look at that, thanks for the share ❤️ 

Is there any documentation around this functionlity?

**Comment by luisburigo** [comment] 2024-02-28 17:06
> > @luisburigo I just took a look at your code and you didn't add contract B into the call so the library doesn't know how to decode it. You should do this:
> > ```ts
> >     const contractAAbi = ContractAAbi__factory.connect(contractA, wallet);
> >     const contractBAbi = ContractBAbi__factory.connect(contractB, wallet);
> >     const result = await contractAAbi.functions.method({
> >         value: contractB
> >     })
> >     .addContracts([contractBAbi]) //  <------- this was missing
> >     .txParams({
> >         gasPrice: 1,
> >         gasLimit: 1_000_000,
> >     })
> > ```
> 
> Look at that, thanks for the share ❤️
> 
> Link to the [documentation](https://docs.fuel.network/docs/fuels-ts/contracts/inter-contract-calls/#inter-contract-calls-using-the-sdk) on inter-contract calls.

Thanks @petertonysmith94 ❤️❤️

**Comment by arboleya** [comment] 2024-02-29 10:04
Can we close this?

**Closed** 2024-03-04 13:26 UTC
Labels: bug
